# fastlane/Fastfile

# Define defult platform as iOS
default_platform(:ios)

platform :ios do

    desc "Run all tests ve report the results"
    lane :run_tests do
        scan(
            scheme: "VideoEditor",
            destination: "platform=iOS Simulator,name=iPhone 17 Pro Max,OS=latest",
            clean: true,
            build_for_testing: true,
            output_directory: "fastlane/test_output"
        
        )
    end
end
